# Generated by Django 4.2.16 on 2024-11-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_build', '0002_remove_resume_job_title_remove_resume_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='city',
            field=models.CharField(default='DefaultCityName', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='country',
            field=models.CharField(default='DefaultCountryName', max_length=100),
        ),
    ]
