# Generated by Django 4.2.16 on 2024-11-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_build', '0004_remove_resume_education_remove_resume_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='month',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='year',
        ),
        migrations.AddField(
            model_name='experience',
            name='end_month',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='experience',
            name='end_year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='education',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
