# Generated by Django 4.2.16 on 2024-11-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_build', '0005_remove_experience_month_remove_experience_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='month',
            new_name='end_month',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='year',
            new_name='end_year',
        ),
        migrations.AddField(
            model_name='education',
            name='start_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(default=2000),
        ),
    ]
