# Generated by Django 4.2.16 on 2024-11-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_build', '0007_experience_bullet_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.CharField(default='Undeclared Major', max_length=255),
        ),
        migrations.AddField(
            model_name='education',
            name='school_name',
            field=models.CharField(default='Unknown School', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
