# Generated by Django 4.2.16 on 2024-11-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_build', '0008_education_gpa_education_major_education_school_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='content',
            new_name='scholarships',
        ),
    ]
