# Generated by Django 4.2.16 on 2024-11-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_build', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
