# Generated by Django 5.1.1 on 2024-11-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_build', '0004_alter_job_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='education',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='education',
            name='scholarships',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='bullet_points',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='department_and_role',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_month',
        ),
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(default='Unknown Degree', max_length=255),
        ),
        migrations.AddField(
            model_name='education',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='institution_name',
            field=models.CharField(default='Unknown Company', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
